query loanChunks($loanIds: [String]!) {
  loanChunks(where: { loanId_in: $loanIds }) {
    id
    loanId
    poolId
    rate
    repaidAmount
    borrowedAmount
    lastUpdateTs
    accruedInterest
  }

  _meta {
    block {
      number
      timestamp
      hash
    }
  }
}
