query loansById($loanIds: [String]!) {
  loans(where: { id_in: $loanIds }) {
    id
    loanRequestId
    policyId
    data
    borrowedAmount
  }

  _meta {
    block {
      number
      timestamp
      hash
    }
  }
}
