query loans($policyIds: [String]!) {
  loanRequests(where: { policyId_in: $policyIds }) {
    id
    policyId
    amount
    status
    minAmount
    approvedAmount
    filledAmount
    loanId
    maxPremiumRatePerSec
    receiveOnApprove
  }

  loans(where: { policyId_in: $policyIds }) {
    id
    loanRequestId
    policyId
    data
    borrowedAmount
  }

  _meta {
    block {
      number
      timestamp
      hash
    }
  }
}
