query loansById($loanIds: [String]!) {
  loans(where: { id_in: $loanIds }) {
    id
    loanRequestId
    policyId
    data
    borrowedAmount
    governanceIncentiveFee
    lastUpdateTs
    marketOperatorIncentiveFee
    productOperatorIncentiveFee
    interestCharged
    interestRepaid
    createdAt
  }

  _meta {
    block {
      number
      timestamp
      hash
    }
  }
}
