query main($productIds: [String]!, $managerIds: [String]!, $owner: String!) {
  markets(where: { productId_in: $productIds }) {
    id
    marketId
    title
    author
    aggregatedPools {
      id
      poolList
    }
    productId
    product {
      id
      title
    }
    desiredCover
    capitalToken
    premiumToken
  }

  pools(where: { manager_in: $managerIds }) {
    id
    name
    capitalTokenSymbol
    capitalTokenAddress
    capitalTokenDecimals
    manager
    managerFee
    capitalRequirement
    capitalTokenBalance
    markets {
      id
      title
      product {
        id
        title
      }
    }
  }

  myPolicies: policies(where: { productId_in: $productIds, owner: $owner }) {
    id
    productId
    marketId
    policyId
    owner
    issuer
    balance
    coverage
    premiumDeposit
    underlyingCover
    market {
      capitalToken
      premiumToken
    }
  }

  _meta {
    block {
      number
      timestamp
      hash
    }
  }
}
