query main($author: String!) {
  markets(where: { author: $author }) {
    id
    title
    author
    aggregatedPools {
      id
      poolList
    }
    desiredCover
    capitalToken
  }

  pools(where: { markets_: { id_in: ["0x5cfdd8f4dcbd1ac2d5de1f102fda0b485b3e1f13-33"] } }) {
    id
    name
    capitalTokenSymbol
    capitalTokenAddress
    capitalTokenDecimals
    manager
    markets {
      id
      title
      product {
        id
        title
      }
    }
  }
}
