query main($operatorIds: [String]!) {
  pools(where: { owner_in: $operatorIds }) {
    id
    name
    capitalTokenSymbol
    capitalTokenAddress
    capitalTokenDecimals
    operator
    operatorFee
    owner
    capitalRequirement
    capitalTokenBalance
    data
    details
    markets {
      id
      title
      details
      wording
      premiumToken
      product {
        id
        title
        wording
      }
    }
  }

  _meta {
    block {
      number
      timestamp
      hash
    }
  }
}
