query poolLoanChunks($poolIds: [String]!) {
  loanChunks(where: { poolId_in: $poolIds }) {
    id
    loanId
    poolId
    rate
    repaidAmount
    borrowedAmount
  }

  _meta {
    block {
      number
      timestamp
      hash
    }
  }
}
